[build]
publish = "dist/"
command = "rustup toolchain install nightly && rustup target add wasm32-unknown-unknown && cargo install cargo-make --force && cargo make build"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[redirects]]
from = "/github"
to = "https://github.com/NiklasEi/ecs_leptos_ssg"
status = 302
